//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume-template.list",
			Path:         []string{"volume-template", "list"},
			Use:          "list",
			Short:        "List volume templates",
			Long:         "List volume templates with exact ID/name filters, generic filters and pagination. Available in preview builds.",
			Examples:     []string{"Example - Look up specific templates:\n  agr volume-template list --volume-template-ids volt-a1b2c3d4", "Example - Page through results:\n  agr volume-template list --limit 20 --offset 20"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeVolumeTemplateListResponse",
				Description: "DescribeVolumeTemplateListResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume-template"}, Use: "volume-template", Short: "Manage sandbox volume templates", Long: "Manage sandbox volume templates. A template derives or reuses a concrete volume per reuse key instead of binding one fixed path."},
		},
		API: apicli.APISpec{
			Action:       "DescribeVolumeTemplateList",
			RequestType:  "DescribeVolumeTemplateListRequest",
			ResponseType: "DescribeVolumeTemplateListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeTemplateIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-ids", Flag: "volume-template-ids", Usage: "Volume template IDs to match exactly. Repeat the flag or pass a comma-separated list.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "VolumeTemplateNames",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-names", Flag: "volume-template-names", Usage: "Volume template names to match exactly. Repeat the flag or pass a comma-separated list.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Generic filters as a JSON array, @file, or - for stdin. Different filters are ANDed, values inside one filter are ORed.", Format: "[{\"Name\":\"<name>\",\"Values\":[\"<value>\"]}]", Fields: []string{"Name: filter name", "Values: values ORed inside one filter"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset, starting at 0.", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Number of results per page, at most 100.", Type: command.FlagInt},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
