// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.list",
			Path:         []string{"deployment", "list"},
			Use:          "list",
			Short:        "List deployments",
			Examples:     []string{"agr deployment list", "agr deployment list --filters '[{\"Name\":\"status\",\"Values\":[\"ACTIVE\"]}]'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeDeploymentListResponse",
				Description: "Deployment list response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "DescribeDeploymentList",
			RequestType:  "DescribeDeploymentListRequest",
			ResponseType: "DescribeDeploymentListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "分页偏移量，默认 0，必须大于等于 0。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "分页返回数量，默认 20，范围 1..200。", Type: command.FlagInt},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Filters JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
