//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume.delete",
			Path:         []string{"volume", "delete"},
			Use:          "delete",
			Short:        "Delete a volume",
			Long:         "Delete a volume by ID or name. Deletion fails while the volume is still mounted. Available in preview builds.",
			Examples:     []string{"Example - Delete by name:\n  agr volume delete --volume-name agent-workspace"},
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteVolumeResponse",
				Description: "DeleteVolumeResponse response.",
				Effects:     []string{"delete:volume"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume"}, Use: "volume", Short: "Manage sandbox volumes", Long: "Manage sandbox volumes. A volume binds one concrete storage location that sandbox instances can mount."},
		},
		API: apicli.APISpec{
			Action:       "DeleteVolume",
			RequestType:  "DeleteVolumeRequest",
			ResponseType: "DeleteVolumeResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-id", Flag: "volume-id", Usage: "Volume ID. Provide either this or --volume-name.", Type: command.FlagString},
				},
			},
			{
				Name:   "VolumeName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-name", Flag: "volume-name", Usage: "Volume name. Provide either this or --volume-id.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
