//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume.list",
			Path:         []string{"volume", "list"},
			Use:          "list",
			Short:        "List volumes",
			Long:         "List volumes with exact ID/name filters, generic filters and pagination. Available in preview builds.",
			Examples:     []string{"Example - Look up specific volumes:\n  agr volume list --volume-ids vol-a1b2c3d4 --volume-ids vol-e5f6g7h8", "Example - Page through results:\n  agr volume list --limit 20 --offset 20"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeVolumeListResponse",
				Description: "DescribeVolumeListResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume"}, Use: "volume", Short: "Manage sandbox volumes", Long: "Manage sandbox volumes. A volume binds one concrete storage location that sandbox instances can mount."},
		},
		API: apicli.APISpec{
			Action:       "DescribeVolumeList",
			RequestType:  "DescribeVolumeListRequest",
			ResponseType: "DescribeVolumeListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "volume-ids", Flag: "volume-ids", Usage: "Volume IDs to match exactly. Repeat the flag or pass a comma-separated list.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "VolumeNames",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "volume-names", Flag: "volume-names", Usage: "Volume names to match exactly. Repeat the flag or pass a comma-separated list.", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Generic filters as a JSON array, @file, or - for stdin. Different filters are ANDed, values inside one filter are ORed.", Format: "[{\"Name\":\"<name>\",\"Values\":[\"<value>\"]}]", Fields: []string{"Name: filter name", "Values: values ORed inside one filter"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset, starting at 0.", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Number of results per page, at most 100.", Type: command.FlagInt},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
