// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.get",
			Path:         []string{"session", "get"},
			Use:          "get",
			Short:        "Describe a session",
			Examples:     []string{"Example - Describe a session:\n  agr session get --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSessionResponse",
				Description: "DescribeSessionResponse response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "DescribeSession",
			RequestType:  "DescribeSessionRequest",
			ResponseType: "DescribeSessionResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "NumRecentEvents",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "num-recent-events", Flag: "num-recent-events", Usage: "返回最近事件数量，默认为 0，最大值为 200。", Type: command.FlagInt},
				},
			},
			{
				Name:   "AfterTimestamp",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "after-timestamp", Flag: "after-timestamp", Usage: "事件起始时间，RFC3339 格式，最大长度 64 字符。", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
