// Code generated by cobragen; DO NOT EDIT.

package updatetitle

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "session.update-title",
			Path:         []string{"session", "update-title"},
			Use:          "update-title",
			Short:        "Update a session title",
			Examples:     []string{"Example - Update a session title with the dedicated API:\n  agr session update-title --space-id space-a1b2c3d4 --user-id user-123 --session-id session-123 --title 'Resolved request'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "ModifySessionTitleResponse",
				Description: "ModifySessionTitleResponse response.",
				Effects:     []string{"update:session"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"session"}, Use: "session", Short: "Manage sessions"},
		},
		API: apicli.APISpec{
			Action:       "ModifySessionTitle",
			RequestType:  "ModifySessionTitleRequest",
			ResponseType: "ModifySessionTitleResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "SpaceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "space-id", Flag: "space-id", Usage: "会话所属空间 ID。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "UserId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "user-id", Flag: "user-id", Usage: "用户 ID。可通过调用方业务系统接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "SessionId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "session-id", Flag: "session-id", Usage: "会话 ID。可通过 CreateSession 或 DescribeSessions 接口获取。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Title",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "title", Flag: "title", Usage: "会话标题，最大长度 255 字符。 (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "AgentId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "agent-id", Flag: "agent-id", Usage: "Agent ID。可选。", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
