// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.create",
			Path:         []string{"deployment", "create"},
			Use:          "create",
			Short:        "Create a deployment",
			Long:         "Create a remotely managed Deployment. Complex configuration fields accept a JSON value, @file, or - for stdin.",
			Examples:     []string{"agr deployment create --deployment-name workspace-service --tool-id sdt-a1b2c3d4", "agr deployment create --deployment-name workspace-service --scaling-configuration '{\"MinInstanceCount\":0,\"MaxInstanceCount\":10,\"MaxInstanceRequestConcurrency\":100}'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateDeploymentResponse",
				Description: "Deployment create response.",
				Effects:     []string{"create:deployment"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "CreateDeployment",
			RequestType:  "CreateDeploymentRequest",
			ResponseType: "CreateDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-name", Flag: "deployment-name", Usage: "Unique DNS-1123 deployment name (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "ToolId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Flag: "tool-id", Usage: "Associated sandbox tool ID", Type: command.FlagString},
				},
			},
			{
				Name:   "ScalingConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "scaling-configuration", Flag: "scaling-configuration", Usage: "ScalingConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "LifecycleConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "lifecycle-configuration", Flag: "lifecycle-configuration", Usage: "LifecycleConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "AffinityConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "affinity-configuration", Flag: "affinity-configuration", Usage: "AffinityConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
