// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.create",
			Path:         []string{"deployment", "create"},
			Use:          "create",
			Short:        "Create a deployment",
			Long:         "Create a remotely managed Deployment. Complex configuration fields accept a JSON value, @file, or - for stdin.",
			Examples:     []string{"Example - Scale to zero after five idle minutes:\n  agr deployment create \\\n    --deployment-name workspace-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --scaling-configuration '{\"MinInstanceCount\":0,\"MaxInstanceCount\":10,\"MaxInstanceRequestConcurrency\":100}' \\\n    --lifecycle-configuration '{\"IdleTimeoutSeconds\":300,\"IdleAction\":\"STOP\"}'", "Example - Keep two instances active:\n  agr deployment create \\\n    --deployment-name latency-sensitive-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --scaling-configuration '{\"MinInstanceCount\":2,\"MaxInstanceCount\":20,\"MaxInstanceRequestConcurrency\":200}'", "Example - Prefer the same instance for requests sharing an affinity ID:\n  agr deployment create \\\n    --deployment-name session-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --affinity-configuration '{\"Mode\":\"BEST_EFFORT\",\"HeaderName\":\"X-Tencent-Agr-Affinity-Id\"}'", "Example - Fail instead of selecting another instance for an affinity ID:\n  agr deployment create \\\n    --deployment-name strict-session-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --affinity-configuration '{\"Mode\":\"STRICT\",\"HeaderName\":\"X-Tencent-Agr-Affinity-Id\"}'", "Example - Give each affinity ID an exclusive, non-migrating instance:\n  agr deployment create \\\n    --deployment-name exclusive-session-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --affinity-configuration '{\"Mode\":\"EXCLUSIVE\",\"HeaderName\":\"X-Tencent-Agr-Affinity-Id\"}'", "Example - Load configuration from files and capture the Deployment ID:\n  deployment_id=$(agr deployment create \\\n    --deployment-name workspace-service \\\n    --tool-id sdt-a1b2c3d4 \\\n    --scaling-configuration @scaling.json \\\n    --lifecycle-configuration @lifecycle.json \\\n    --tags @tags.json \\\n    -o json --jq '.Data.Deployment.DeploymentId')"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateDeploymentResponse",
				Description: "Deployment create response.",
				Effects:     []string{"create:deployment"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "CreateDeployment",
			RequestType:  "CreateDeploymentRequest",
			ResponseType: "CreateDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-name", Flag: "deployment-name", Usage: "Unique DNS-1123 deployment name (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "ToolId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Flag: "tool-id", Usage: "Associated sandbox tool ID", Type: command.FlagString},
				},
			},
			{
				Name:   "ScalingConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "scaling-configuration", Flag: "scaling-configuration", Usage: "Scaling configuration JSON object, @file, or - for stdin. The object and individual fields are optional; omitted fields use service defaults.", Format: "{\"MinInstanceCount\":<integer>,\"MaxInstanceCount\":<integer>,\"MaxInstanceRequestConcurrency\":<integer>}", Fields: []string{"MinInstanceCount: minimum number of active Sandbox Instances; >= 0; default: 0", "MaxInstanceCount: maximum number of active Sandbox Instances; >= 1 and >= MinInstanceCount; default: 10", "MaxInstanceRequestConcurrency: maximum concurrent Deployment request or connection leases per active Sandbox Instance; >= 1; default: 100"}, Type: command.FlagString},
				},
			},
			{
				Name:   "LifecycleConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "lifecycle-configuration", Flag: "lifecycle-configuration", Usage: "Idle lifecycle configuration JSON object, @file, or - for stdin. The object and individual fields are optional; omitted fields use service defaults.", Format: "{\"IdleTimeoutSeconds\":<integer>,\"IdleAction\":\"<action>\"}", Fields: []string{"IdleTimeoutSeconds: idle seconds after the last active Deployment request or connection before IdleAction; >= 30 with no fixed upper limit; default: 300", "IdleAction: STOP releases the Sandbox Instance; PAUSE preserves its state; default: STOP"}, Type: command.FlagString},
				},
			},
			{
				Name:   "AffinityConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "affinity-configuration", Flag: "affinity-configuration", Usage: "Session affinity configuration JSON object, @file, or - for stdin. Affinity is disabled by default.", Format: "{\"Mode\":\"<mode>\",\"HeaderName\":\"<header-name>\"}", Fields: []string{"Mode: affinity behavior\n  - BEST_EFFORT: prefer the previous Sandbox Instance; select another one when unavailable\n  - STRICT: require the previous Sandbox Instance; fail instead of selecting another one\n  - EXCLUSIVE: dedicate one non-migrating Sandbox Instance to each affinity ID\n  - Empty or omitted: disable affinity", "HeaderName: request and response header carrying the affinity ID\n  - Default when Mode is enabled: X-Tencent-Agr-Affinity-Id\n  - Constraint: a non-reserved HTTP field name of 1-128 ASCII bytes; omit when affinity is disabled"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Resource tags as a JSON array, @file, or - for stdin. Omit for no tags.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
