// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.delete",
			Path:         []string{"deployment", "delete"},
			Use:          "delete <deployment-id>",
			Short:        "Delete a deployment",
			Long:         "Delete a remotely managed Deployment. By default, return after the delete request is accepted. Use --wait to poll until deletion completes or fails.",
			Examples:     []string{"Example - Request deletion and return immediately:\n  agr deployment delete dpl-a1b2c3d4", "Example - Wait until deletion completes or fails:\n  agr deployment delete dpl-a1b2c3d4 --wait"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "deployment-id", Required: true, Description: "Deployment ID."},
			},
			Output: command.OutputSpec{
				DataType:    "DeleteDeploymentResponse",
				Description: "Deployment delete response.",
				Effects:     []string{"delete:deployment"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "DeleteDeployment",
			RequestType:  "DeleteDeploymentRequest",
			ResponseType: "DeleteDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
