// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:                "deployment.update",
			Path:              []string{"deployment", "update"},
			Use:               "update <deployment-id>",
			Short:             "Update a deployment",
			Long:              "Update the mutable configuration of a remotely managed Deployment. Provided configuration objects replace their current values in full.",
			PreserveFlagOrder: true,
			Examples:          []string{"Example - Increase active capacity:\n  agr deployment update dpl-a1b2c3d4 \\\n    --scaling-configuration '{\"MinInstanceCount\":2,\"MaxInstanceCount\":20,\"MaxInstanceRequestConcurrency\":200}'", "Example - Pause idle instances after ten minutes and retain their state:\n  agr deployment update dpl-a1b2c3d4 \\\n    --lifecycle-configuration '{\"IdleTimeoutSeconds\":600,\"IdleAction\":\"PAUSE\"}'", "Example - Stop idle instances after five minutes:\n  agr deployment update dpl-a1b2c3d4 \\\n    --lifecycle-configuration '{\"IdleTimeoutSeconds\":300,\"IdleAction\":\"STOP\"}'", "Example - Replace all tags:\n  agr deployment update dpl-a1b2c3d4 \\\n    --tags '[{\"Key\":\"env\",\"Value\":\"production\"},{\"Key\":\"team\",\"Value\":\"agent-platform\"}]'", "Example - Clear all tags:\n  agr deployment update dpl-a1b2c3d4 --tags '[]'"},
			SupportsJSON:      true,
			Args: []command.ArgSpec{
				{Name: "deployment-id", Required: true, Description: "Deployment ID."},
			},
			Output: command.OutputSpec{
				DataType:    "ModifyDeploymentResponse",
				Description: "Deployment update response.",
				Effects:     []string{"update:deployment"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "ModifyDeployment",
			RequestType:  "ModifyDeploymentRequest",
			ResponseType: "ModifyDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-id", Positional: true},
				},
			},
			{
				Name:   "ScalingConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "scaling-configuration", Flag: "scaling-configuration", Usage: "Complete scaling configuration JSON object, @file, or - for stdin. Providing it replaces the current scaling configuration; include all three fields because update does not apply create defaults.", Format: "{\"MinInstanceCount\":<integer>,\"MaxInstanceCount\":<integer>,\"MaxInstanceRequestConcurrency\":<integer>}", Fields: []string{"MinInstanceCount: minimum number of active Sandbox Instances; >= 0", "MaxInstanceCount: maximum number of active Sandbox Instances; >= 1 and >= MinInstanceCount", "MaxInstanceRequestConcurrency: maximum concurrent Deployment request or connection leases per active Sandbox Instance; >= 1"}, Type: command.FlagString},
				},
			},
			{
				Name:   "LifecycleConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "lifecycle-configuration", Flag: "lifecycle-configuration", Usage: "Complete idle lifecycle configuration JSON object, @file, or - for stdin. Providing it replaces the current lifecycle configuration; include both fields because update does not apply create defaults.", Format: "{\"IdleTimeoutSeconds\":<integer>,\"IdleAction\":\"<action>\"}", Fields: []string{"IdleTimeoutSeconds: idle seconds after the last active Deployment request or connection before IdleAction; >= 30 with no fixed upper limit", "IdleAction: STOP releases the Sandbox Instance; PAUSE preserves its state"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Resource tags as a JSON array, @file, or - for stdin. Providing --tags replaces all tags; [] clears all tags; omit --tags to leave tags unchanged.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
