// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.update",
			Path:         []string{"deployment", "update"},
			Use:          "update <deployment-id>",
			Short:        "Update a deployment",
			Long:         "Update the mutable configuration of a remotely managed Deployment. Provided configuration objects replace their current values in full.",
			Examples:     []string{"agr deployment update dpl-a1b2c3d4 --scaling-configuration '{\"MinInstanceCount\":0,\"MaxInstanceCount\":10,\"MaxInstanceRequestConcurrency\":100}'", "agr deployment update dpl-a1b2c3d4 --tags '[{\"Key\":\"env\",\"Value\":\"test\"}]'"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "deployment-id", Required: true, Description: "Deployment ID."},
			},
			Output: command.OutputSpec{
				DataType:    "ModifyDeploymentResponse",
				Description: "Deployment update response.",
				Effects:     []string{"update:deployment"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "ModifyDeployment",
			RequestType:  "ModifyDeploymentRequest",
			ResponseType: "ModifyDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-id", Positional: true},
				},
			},
			{
				Name:   "ScalingConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "scaling-configuration", Flag: "scaling-configuration", Usage: "Complete ScalingConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "LifecycleConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "lifecycle-configuration", Flag: "lifecycle-configuration", Usage: "Complete LifecycleConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Complete Tags JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
