//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume-template.create",
			Path:         []string{"volume-template", "create"},
			Use:          "create",
			Short:        "Create a volume template",
			Long:         "Create a volume template. Templates derive or reuse concrete volumes per reuse key instead of binding one fixed path. Available in preview builds.",
			Examples:     []string{"Example - Derive one COS prefix per session:\n  agr volume-template create --volume-template-name agent-session-workspace --access-mode ReadWriteMany --reclaim-policy Delete --storage-type Cos --storage-spec '{\"Cos\":{\"Endpoint\":\"cos.ap-guangzhou.myqcloud.com\",\"BucketName\":\"agent-data-1250000000\",\"BucketPathPattern\":\"sessions/${reuse_key}\"}}' --volume-name-pattern 'agent-workspace-${reuse_key}'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateVolumeTemplateResponse",
				Description: "CreateVolumeTemplateResponse response.",
				Effects:     []string{"create:volume-template"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume-template"}, Use: "volume-template", Short: "Manage sandbox volume templates", Long: "Manage sandbox volume templates. A template derives or reuses a concrete volume per reuse key instead of binding one fixed path."},
		},
		API: apicli.APISpec{
			Action:       "CreateVolumeTemplate",
			RequestType:  "CreateVolumeTemplateRequest",
			ResponseType: "CreateVolumeTemplateResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "VolumeTemplateName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-name", Flag: "volume-template-name", Usage: "Volume template name, unique within the account. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "AccessMode",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "access-mode", Flag: "access-mode", Usage: "Access mode: ReadWriteOnce, ReadWriteMany or ReadOnlyMany. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "ReclaimPolicy",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "reclaim-policy", Flag: "reclaim-policy", Usage: "Reclaim policy: Retain keeps derived volumes after the sandbox is deleted, Delete removes them. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "StorageSpec",
				Required: true,
				Parser:   "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "storage-spec", Flag: "storage-spec", Usage: "Template storage spec as JSON, @file, or - for stdin. Exactly one backend must be set and it must match --storage-type. (required)", Format: "{\"Cos\":{\"Endpoint\":\"<endpoint>\",\"BucketName\":\"<bucket>\",\"BucketPathPattern\":\"<pattern>\"}} | {\"Cfs\":{\"FileSystemId\":\"<cfs-id>\",\"PathPattern\":\"<pattern>\"}}", Fields: []string{"Cos: COS bucket path pattern, may contain ${reuse_key}", "Cfs: CFS path pattern, may contain ${reuse_key}"}, Type: command.FlagString},
				},
			},
			{
				Name:     "StorageType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "storage-type", Flag: "storage-type", Usage: "Storage backend type: Cos or Cfs. Must match the field set in the storage payload. (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "VolumeNamePattern",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-name-pattern", Flag: "volume-name-pattern", Usage: "Name pattern for derived volumes; may contain ${reuse_key}.", Type: command.FlagString},
				},
			},
			{
				Name:   "DefaultCapacity",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "default-capacity", Flag: "default-capacity", Usage: "Reserved capacity field; ignored by the COS and CFS backends.", Type: command.FlagString},
				},
			},
			{
				Name:   "StorageRoleArn",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "storage-role-arn", Flag: "storage-role-arn", Usage: "Role ARN used to access the underlying storage.", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as a JSON array, @file, or - for stdin. The list replaces existing tags.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
			{
				Name:   "ClientToken",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "client-token", Flag: "client-token", Usage: "Idempotency token, at most 64 characters.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
