//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume.update",
			Path:         []string{"volume", "update"},
			Use:          "update",
			Short:        "Update a volume",
			Long:         "Update volume tags. Storage, access mode and name cannot be changed. Identify the volume by ID or name. Available in preview builds.",
			Examples:     []string{"Example - Replace the tag set:\n  agr volume update --volume-name agent-workspace --tags '[{\"Key\":\"team\",\"Value\":\"agents\"}]'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "UpdateVolumeResponse",
				Description: "UpdateVolumeResponse response.",
				Effects:     []string{"update:volume"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume"}, Use: "volume", Short: "Manage sandbox volumes", Long: "Manage sandbox volumes. A volume binds one concrete storage location that sandbox instances can mount."},
		},
		API: apicli.APISpec{
			Action:       "UpdateVolume",
			RequestType:  "UpdateVolumeRequest",
			ResponseType: "UpdateVolumeResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-id", Flag: "volume-id", Usage: "Volume ID. Provide either this or --volume-name.", Type: command.FlagString},
				},
			},
			{
				Name:   "VolumeName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-name", Flag: "volume-name", Usage: "Volume name. Provide either this or --volume-id.", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as a JSON array, @file, or - for stdin. The list replaces existing tags.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
