// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "deployment.get",
			Path:         []string{"deployment", "get"},
			Use:          "get <deployment-id>",
			Short:        "Describe a deployment",
			Examples:     []string{"Example - Inspect the Deployment in a human-readable form:\n  agr deployment get dpl-a1b2c3d4", "Example - Print the complete API response:\n  agr deployment get dpl-a1b2c3d4 -o json", "Example - Extract the current status for a script:\n  agr deployment get dpl-a1b2c3d4 -o json --jq '.Data.Deployment.Status'"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "deployment-id", Required: true, Description: "Deployment ID."},
			},
			Output: command.OutputSpec{
				DataType:    "DescribeDeploymentResponse",
				Description: "Deployment details response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"deployment"}, Use: "deployment", Short: "Manage deployments", Long: "Manage deployments and related data-plane workflows."},
		},
		API: apicli.APISpec{
			Action:       "DescribeDeployment",
			RequestType:  "DescribeDeploymentRequest",
			ResponseType: "DescribeDeploymentResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "DeploymentId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "deployment-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
