//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume-template.update",
			Path:         []string{"volume-template", "update"},
			Use:          "update",
			Short:        "Update a volume template",
			Long:         "Update volume template tags and default capacity. Storage spec, access mode and reclaim policy cannot be changed. Available in preview builds.",
			Examples:     []string{"Example - Replace the tag set:\n  agr volume-template update --volume-template-id volt-a1b2c3d4 --tags '[{\"Key\":\"team\",\"Value\":\"agents\"}]'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "UpdateVolumeTemplateResponse",
				Description: "UpdateVolumeTemplateResponse response.",
				Effects:     []string{"update:volume-template"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume-template"}, Use: "volume-template", Short: "Manage sandbox volume templates", Long: "Manage sandbox volume templates. A template derives or reuses a concrete volume per reuse key instead of binding one fixed path."},
		},
		API: apicli.APISpec{
			Action:       "UpdateVolumeTemplate",
			RequestType:  "UpdateVolumeTemplateRequest",
			ResponseType: "UpdateVolumeTemplateResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeTemplateId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-id", Flag: "volume-template-id", Usage: "Volume template ID. Provide either this or --volume-template-name.", Type: command.FlagString},
				},
			},
			{
				Name:   "VolumeTemplateName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-name", Flag: "volume-template-name", Usage: "Volume template name. Provide either this or --volume-template-id.", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as a JSON array, @file, or - for stdin. The list replaces existing tags.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
			{
				Name:   "DefaultCapacity",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "default-capacity", Flag: "default-capacity", Usage: "Reserved capacity field; ignored by the COS and CFS backends.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
