// Code generated by cobragen; DO NOT EDIT.

package pause

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.pause",
			Path:         []string{"instance", "pause"},
			Use:          "pause <instance-id>",
			Short:        "Pause instance",
			Long:         "Pause a sandbox instance. Use --memory to preserve process and memory state; omit it to use the service default.",
			Examples:     []string{"agr instance pause ins-xxxx", "agr instance pause ins-xxxx --memory"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "instance-id", Required: true, Description: "Sandbox instance ID."},
			},
			Output: command.OutputSpec{
				DataType:    "PauseSandboxInstanceResponse",
				Description: "Instance pause response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "PauseSandboxInstance",
			RequestType:  "PauseSandboxInstanceRequest",
			ResponseType: "PauseSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "InstanceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "instance-id", Positional: true},
				},
			},
			{
				Name:   "Memory",
				Parser: "common.default_bool",
				Inputs: []apicli.InputSpec{
					{Name: "memory", Flag: "memory", Usage: "Preserve process and memory state; use --memory=false for disk-only pause", Type: command.FlagBool},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
