package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apimeta"
)

const generatedMarker = "// Code generated by cobragen; DO NOT EDIT."

func selectedChannel(channels []apimeta.Channel) apimeta.Channel {
	if len(channels) > 0 {
		return channels[0]
	}
	return apimeta.Stable
}

func previewPath(path string) string {
	if strings.HasSuffix(path, ".generated.go") {
		return strings.TrimSuffix(path, ".generated.go") + "_preview.generated.go"
	}
	return strings.TrimSuffix(path, ".go") + "_preview.go"
}

func channelOutputs(stable, preview map[string][]byte) map[string][]byte {
	files := map[string][]byte{}
	for path, data := range stable {
		if bytes.Equal(data, preview[path]) {
			files[path] = data
		} else {
			files[path] = append([]byte("//go:build !preview\n\n"), data...)
		}
	}
	for path, data := range preview {
		if !bytes.Equal(data, stable[path]) {
			files[previewPath(path)] = append([]byte("//go:build preview\n\n"), data...)
		}
	}
	return files
}

func obsoleteOutputs(expected map[string][]byte) ([]string, error) {
	var obsolete []string
	for _, root := range []string{"internal/apimeta", "internal/commands"} {
		err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
			if os.IsNotExist(err) {
				return nil
			}
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			name := entry.Name()
			managed := (root == "internal/apimeta" && (name == "generated_model.go" || name == "generated_model_preview.go")) || (root == "internal/commands" && (name == "api.generated.go" || name == "api_preview.generated.go" || path == "internal/commands/registry.generated.go" || path == "internal/commands/registry_preview.generated.go"))
			if !managed {
				return nil
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.Contains(data, []byte(generatedMarker)) {
				return fmt.Errorf("refusing to manage unmarked file %s", path)
			}
			if _, ok := expected[path]; !ok {
				obsolete = append(obsolete, path)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	slices.Sort(obsolete)
	return obsolete, nil
}

func registrySymbolForCommandDir(dir string, channels ...apimeta.Channel) (string, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return "GeneratedModule", nil
	}
	if err != nil {
		return "", err
	}
	ctx := build.Default
	ctx.BuildTags = nil
	if selectedChannel(channels) == apimeta.Preview {
		ctx.BuildTags = []string{"preview"}
	}
	modules := 0
	hasCommand := false
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return "", err
		}
		if bytes.Contains(data, []byte(generatedMarker)) {
			continue
		}
		match, err := ctx.MatchFile(dir, name)
		if err != nil {
			return "", err
		}
		if !match {
			continue
		}
		if name == "command.go" || name == "command_preview.go" {
			hasCommand = true
		}
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, name), data, 0)
		if err != nil {
			return "", err
		}
		for _, decl := range file.Decls {
			if fn, ok := decl.(*ast.FuncDecl); ok && fn.Recv == nil && fn.Name.Name == "Module" {
				modules++
			}
		}
	}
	if modules == 1 {
		return "Module", nil
	}
	if modules > 1 || hasCommand {
		return "", fmt.Errorf("%s: expected one Module() for %s, found %d", dir, selectedChannel(channels), modules)
	}
	return "GeneratedModule", nil
}
