//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume.create",
			Path:         []string{"volume", "create"},
			Use:          "create",
			Short:        "Create a volume",
			Long:         "Create a standalone sandbox volume bound to a concrete storage location. Available in preview builds.",
			Examples:     []string{"Example - Bind an existing COS bucket path:\n  agr volume create --volume-name agent-workspace --access-mode ReadWriteMany --storage-type Cos --storage '{\"Cos\":{\"Endpoint\":\"cos.ap-guangzhou.myqcloud.com\",\"BucketName\":\"agent-data-1250000000\",\"BucketPath\":\"workspaces/agent\"}}' --storage-role-arn qcs::cam::uin/100000000001:roleName/AGSCOSRole", "Example - Let the service provision a disk:\n  agr volume create --volume-name agent-scratch --access-mode ReadWriteOnce --storage-type AgentCbs --storage '{\"AgentCbs\":{\"Capacity\":\"20Gi\"}}'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateVolumeResponse",
				Description: "CreateVolumeResponse response.",
				Effects:     []string{"create:volume"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume"}, Use: "volume", Short: "Manage sandbox volumes", Long: "Manage sandbox volumes. A volume binds one concrete storage location that sandbox instances can mount."},
		},
		API: apicli.APISpec{
			Action:       "CreateVolume",
			RequestType:  "CreateVolumeRequest",
			ResponseType: "CreateVolumeResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "VolumeName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-name", Flag: "volume-name", Usage: "Volume name, unique within the account. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "AccessMode",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "access-mode", Flag: "access-mode", Usage: "Access mode: ReadWriteOnce, ReadWriteMany or ReadOnlyMany. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "StorageType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "storage-type", Flag: "storage-type", Usage: "Storage backend type: Cos, Cfs or AgentCbs. Must match the field set in the storage payload. (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "Storage",
				Required: true,
				Parser:   "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "storage", Flag: "storage", Usage: "Concrete storage payload as JSON, @file, or - for stdin. Exactly one backend must be set and it must match --storage-type. (required)", Format: "{\"Cos\":{\"Endpoint\":\"<endpoint>\",\"BucketName\":\"<bucket>\",\"BucketPath\":\"<path>\"}} | {\"Cfs\":{\"FileSystemId\":\"<cfs-id>\",\"Path\":\"<path>\"}} | {\"AgentCbs\":{\"Capacity\":\"<size>\"}}", Fields: []string{"Cos: existing COS bucket path", "Cfs: existing CFS file system path", "AgentCbs: disk provisioned by the service"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as a JSON array, @file, or - for stdin. The list replaces existing tags.", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Fields: []string{"Key: tag key", "Value: tag value"}, Type: command.FlagString},
				},
			},
			{
				Name:   "ClientToken",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "client-token", Flag: "client-token", Usage: "Idempotency token, at most 64 characters.", Type: command.FlagString},
				},
			},
			{
				Name:   "StorageRoleArn",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "storage-role-arn", Flag: "storage-role-arn", Usage: "Role ARN used to access the underlying storage.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
