//go:build preview

// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "volume-template.delete",
			Path:         []string{"volume-template", "delete"},
			Use:          "delete",
			Short:        "Delete a volume template",
			Long:         "Delete a volume template by ID or name. Deletion fails while active volumes still reference it. Available in preview builds.",
			Examples:     []string{"Example - Delete by name:\n  agr volume-template delete --volume-template-name agent-session-workspace"},
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DeleteVolumeTemplateResponse",
				Description: "DeleteVolumeTemplateResponse response.",
				Effects:     []string{"delete:volume-template"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"volume-template"}, Use: "volume-template", Short: "Manage sandbox volume templates", Long: "Manage sandbox volume templates. A template derives or reuses a concrete volume per reuse key instead of binding one fixed path."},
		},
		API: apicli.APISpec{
			Action:       "DeleteVolumeTemplate",
			RequestType:  "DeleteVolumeTemplateRequest",
			ResponseType: "DeleteVolumeTemplateResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "VolumeTemplateId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-id", Flag: "volume-template-id", Usage: "Volume template ID. Provide either this or --volume-template-name.", Type: command.FlagString},
				},
			},
			{
				Name:   "VolumeTemplateName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "volume-template-name", Flag: "volume-template-name", Usage: "Volume template name. Provide either this or --volume-template-id.", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
